import { SUBJECTS } from './subjects.js';
import { TYPE_NAMES } from './academy-data.js';
import { CONTENT_DATE } from './academy-sources.js';
import { RECALL_AUDIT_NOTES } from './fund-recall-data.js';
import { paperSize, questionType } from './engine.js';

export const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const letters = answer => answer == null ? '未作答' : (Array.isArray(answer) ? answer : [answer]).map(n=>'ABCD'[n]).join('、');
export const sourceLabel = q => q.sourceKind === 'recall' ? '回忆真题 · 重述' : q.sourceKind === 'sample' ? '历史样卷 · 重述' : q.variantFamily ? '原创计算 · 参数变式' : '原创训练';
const button = (label,action,attributes='',style='secondary') => `<button class="${style}" data-action="${action}" ${attributes}>${label}</button>`;
const link = s => `<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a>`;
const heading = (eyebrow,title,description) => `<div class="page-heading"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${description}</p></div></div>`;
const countHistorical = subject => subject.QUESTIONS.filter(q=>['recall','sample'].includes(q.sourceKind)).length;
export function yearOptions(subject,selected=0) {
  return `<option value="0">全部年份</option>${[...new Set(subject.QUESTIONS.filter(q=>q.year).map(q=>q.year))].sort((a,b)=>b-a).map(year=>`<option value="${year}" ${Number(selected)===year?'selected':''}>${year}年</option>`).join('')}`;
}
export function learningHome(subject,state,reading,resume,grade) {
  const bank=subject.QUESTIONS,attempted=Object.keys(state.progress).length;
  const correct=Object.values(state.progress).reduce((sum,p)=>sum+p.correct,0),attempts=Object.values(state.progress).reduce((sum,p)=>sum+p.attempts,0);
  const wrong=bank.filter(q=>state.progress[q.id]?.wrong).length;
  const next=subject.LESSONS.find(l=>l.id===reading.last&&!reading.done.includes(l.id))||subject.LESSONS.find(l=>!reading.done.includes(l.id))||subject.LESSONS[0];
  const chapters=Object.entries(subject.CHAPTERS).map(([id,ch])=>{
    const questions=bank.filter(q=>q.chapter===Number(id)),done=questions.filter(q=>state.progress[q.id]).length;
    return {id,ch,total:questions.length,done,wrong:questions.filter(q=>state.progress[q.id]?.wrong).length};
  });
  const weak=[...chapters].sort((a,b)=>b.wrong-a.wrong)[0];
  const recent=state.history.find(s=>s.mode==='exam');
  const profileId=subject.id==='options'?'comprehensive':'standard',profile=subject.PROFILES[profileId];
  return `${heading('YOUR LEARNING WORKSPACE',subject.isFund?'中国大陆基金从业资格':subject.id==='options'?'把知识练熟，再从容开考。':subject.name,`${subject.family} / ${subject.name} · 从原理、案例到考场判断`)}${resume}
  <div class="dashboard-kpis"><div><span>本科题库</span><strong>${bank.length}<small> 道</small></strong><p>章节训练与计算案例</p></div><div><span>系统课程</span><strong>${subject.LESSONS.length}<small> 章</small></strong><p>概念 → 框架 → 案例 → 自测</p></div><div><span>${subject.id==='options'?'可追溯历史样卷':'可追溯回忆真题'}</span><strong>${countHistorical(subject)}<small> 道</small></strong><p>逐题提供年份、题号与出处</p></div></div>
  <div class="dashboard-grid"><div class="dashboard-primary">
    <section class="study-route panel"><div class="section-title"><h2>继续你的学习路径</h2><span>01 / LEARN</span></div><div class="route-body"><span class="route-mark" aria-hidden="true">${String(subject.LESSONS.indexOf(next)+1).padStart(2,'0')}</span><div><span class="tiny-label">${reading.done.length?'接着学':'从第一章开始'} · 约 ${next.minutes} 分钟</span><h3>${esc(next.title)}</h3><p>${esc(next.intro)}</p></div></div><div class="route-footer"><span>已读 ${reading.done.length} / ${subject.LESSONS.length} 章</span>${button(reading.done.length?'继续阅读 →':'开始系统学习 →','course-open',`data-lesson="${next.id}"`,'primary')}</div></section>
    <section class="exam-launch panel"><div class="section-title"><h2>用一份模拟，检验掌握程度</h2><span>02 / PRACTICE</span></div><div class="exam-launch-main"><div><span class="tiny-label">${esc(profile.name)}</span><div class="exam-spec"><strong>${paperSize(profile)}<small>题</small></strong><strong>${profile.minutes}<small>分钟</small></strong><strong>${profile.pass}<small>${subject.id.startsWith('securities')?'% 正确率':'分达标'}</small></strong></div><p>${subject.id==='options'?'综合卷需三个部分分别达到 60%。':subject.isFund?'章节配比为教学安排，每题 1 分。':subject.id.startsWith('securities')?'包含四种题型，题型数量配比为教学设置。':'多选须选全；四种题型按不同分值计分。'}</p></div>${button(subject.id==='options'?'开始综合模拟':'开始本科模拟','start-exam',`data-profile="${profileId}"`,'primary')}</div>${subject.id==='options'?`<div class="exam-levels">${['level1','level2','level3'].map(id=>button(`${subject.PROFILES[id].name} <span>${paperSize(subject.PROFILES[id])} 题 / 20 分钟</span>`,'start-exam',`data-profile="${id}"`,'exam-level')).join('')}</div>`:''}</section>
    <section class="panel chapter-study"><div class="section-title"><h2>把每个章节练扎实</h2>${button('全部章节 →','nav','data-view="practice"','text-button')}</div><div class="chapter-study-list">${chapters.slice(0,6).map(({id,ch,total,done})=>`<button class="study-chapter" data-action="quick-practice" data-chapter="${id}"><span class="chapter-index">${String(id).padStart(2,'0')}</span><span><strong>${esc(ch.name)}</strong><small>已练 ${done} / ${total} 题</small></span><span class="mini-progress" aria-label="已练习 ${Math.round(done/total*100)}%"><i style="width:${done/total*100}%"></i></span><span aria-hidden="true">↗</span></button>`).join('')}</div>${chapters.length>6?`<p class="muted">本科共 ${chapters.length} 个练习模块，更多章节见专项练习。</p>`:''}</section>
  </div><aside class="dashboard-secondary">
    <section class="panel progress-panel"><div class="section-title"><h2>学习概览</h2><span>本机记录</span></div><div class="progress-overview"><div class="progress-ring" style="--progress:${attempted/bank.length*100}%"><div><strong>${attempted}</strong><span>/ ${bank.length} 题</span></div></div><div><strong>${attempts?Math.round(correct/attempts*100)+'%':'—'}</strong><p>累计作答正确率</p></div></div><div class="learning-stats"><span>已读章节<b>${reading.done.length}</b></span><span>待复习错题<b>${wrong}</b></span><span>已完成练习<b>${state.history.length}</b></span></div>${button('开始专项练习','nav','data-view="practice"','secondary full')}</section>
    <section class="panel insight-card"><span class="eyebrow">NEXT BEST STEP</span><h2>${wrong?'先巩固这个薄弱处':'给今天一个小目标'}</h2><p>${wrong?`${esc(weak.ch.name)}有 ${weak.wrong} 道待复习错题。先回看原理，再用同章题检验。`:'读一章原理，做十道练习。理解判断的条件，比只记选项更牢固。'}</p>${button(wrong?'打开错题本 →':'来一组 10 题 →',wrong?'nav':'daily-practice',wrong?'data-view="wrong"':'','text-button')}</section>
    <section class="panel source-summary"><span class="source-dot"></span><h2>真题，有迹可循</h2><p>${subject.id==='options'?'2015 年公开历史样卷，经重述与解析复核。':`本科 ${countHistorical(subject)} 道公开回忆题，标明场次、出处与整理说明。`}</p>${button('打开真题资料 →','nav','data-view="resources"','text-button')}</section>
    <section class="panel compact"><div class="section-title"><h2>最近模拟</h2></div>${recent?`<strong class="recent-score">${grade(recent,bank).score}<small> 分</small></strong><p>${esc(recent.title)}</p>${button('查看成绩与解析','open-result',`data-id="${esc(recent.id)}"`,'text-button')}`:'<p class="muted">完成第一份模拟卷后，成绩会显示在这里。</p>'}</section>
  </aside></div><div class="catalog-entry"><div><span class="eyebrow">EXPLORE THE ACADEMY</span><h2>八个科目，一套完整学习路径。</h2><p>期权开户 / 基金从业 / 证券水平评价 / 期货从业</p></div>${button('浏览全部课程 →','nav','data-view="catalog"','secondary')}</div>`;
}

export function catalogView() {
 const subjects=Object.values(SUBJECTS),total=subjects.reduce((sum,s)=>sum+s.QUESTIONS.length,0),lessons=subjects.reduce((sum,s)=>sum+s.LESSONS.length,0);
 return `${heading('THE KNOWLEDGE ATLAS','选一个方向，系统学下去。',`8 个科目 · ${lessons} 章课程 · ${total.toLocaleString('en-US')} 道训练题`)}<p class="catalog-intro">每科都有从概念到案例的课程、章节练习、来源资料与模拟测试。不同科目的记录独立保存，可以按自己的学习目标切换。</p>${[...new Set(subjects.map(s=>s.family))].map((family,index)=>`<section class="catalog-family"><div class="section-title"><h2><span>${String(index+1).padStart(2,'0')}</span>${family}</h2><span>${subjects.filter(s=>s.family===family).length} 个科目</span></div><div class="subject-cards">${subjects.filter(s=>s.family===family).map(s=>`<a class="subject-card ${s.id}" href="?subject=${s.id}"><span class="tiny-label">${s.id==='options'?'个人投资者知识':s.short}</span><h3>${s.name}</h3><p>${s.LESSONS.slice(0,3).map(l=>l.short).join(' · ')}</p><div class="subject-card-meta"><span>${s.LESSONS.length} 章课程</span><span>${s.QUESTIONS.length} 道题</span><span>${countHistorical(s)} 道${s.id==='options'?'历史样卷':'回忆题'}</span></div><span class="subject-card-link">进入学习空间 <b aria-hidden="true">↗</b></span></a>`).join('')}</div></section>`).join('')}<p class="muted catalog-boundary">回忆题为第三方公开考后整理的重述；历史样卷不代表当前考试原卷。原创参数变式分别标注，题量不等于独立考点数量。</p>`;
}

export function resourcesView(subject,year=0) {
 const all=subject.QUESTIONS.filter(q=>['recall','sample'].includes(q.sourceKind)),qs=all.filter(q=>!year||q.year===year),kind=subject.id==='options'?'sample':'recall';
 const kinds=new Set(qs.map(q=>q.source));
 const primary=Object.entries(subject.SOURCES).filter(([id,s])=>!s.subject&&(s.kind==='official'||!s.publisher));
 return `${heading('VERIFIED SOURCES & EXAM RECOLLECTIONS','真题资料与官方大纲',`${subject.short} · 回忆题、历史样卷与官方范围分别标注`)}<section class="panel provenance-intro"><div><span class="soft-badge">来源核对 ${CONTENT_DATE}</span><h2>${subject.id==='options'?'公开历史样卷，可以对照学习。':'回忆真题，可以逐题追溯。'}</h2><p>${subject.id==='options'?'本站重述 2015 年公开样卷的部分考点并复核解析；当年的题量、时间和业务参数不能直接套入当前考试。':'精选题来自第三方公开考后整理，保留来源题的考查关系与主要数值，使用本站文字重述并独立复核解析。'}不是逐字原题，也不是官方认证试卷。没有经过核实的官方完整历年原卷，不填入虚构真题。</p></div><div class="provenance-numbers"><strong>${all.length}<small> 道可追溯题</small></strong><span>${new Set(all.map(q=>q.source)).size} 个公开来源</span></div><div class="fund-filter-row"><label for="recall-year">${kind==='sample'?'样卷':'回忆题'}年份<select id="recall-year">${yearOptions(subject,year)}</select></label>${button(`练习这 ${qs.length} 道${kind==='sample'?'历史样卷':'回忆题'}`,'recall-practice',`data-year="${year}" data-source="${kind}" ${qs.length?'':'disabled'}`,'primary')}</div></section>
 <div class="section-title"><h2>逐题来源档案</h2><span>${qs.length} 道 / ${kinds.size} 个出处</span></div><section class="recall-list" aria-label="历年回忆题">${qs.map(q=>{const s=subject.SOURCES[q.source];return `<article class="panel recall-question"><div class="question-badges"><span>${q.examSession||q.year+'年'}</span><span>${esc(s.publisher||'公开资料')}</span><span>${sourceLabel(q)}</span><span>${TYPE_NAMES[questionType(q)]}</span></div><h2>${esc(q.stem)}</h2><ol type="A">${q.options.map(o=>`<li>${esc(o)}</li>`).join('')}</ol><details><summary>查看答案、解析与整理说明</summary><p><strong>正确答案：${letters(q.answer)}</strong></p><p>${esc(q.explanation)}</p><p class="muted">${esc(q.reviewNote)}</p></details><p class="source">出处：${link(s)} · 来源页面第 ${q.sourceQuestion} 题 · 非官方原卷</p><a href="?subject=${subject.id}#course/${q.lessonId}" data-action="course-open" data-lesson="${q.lessonId}">回到对应章节 →</a></article>`;}).join('')}</section>
 <details class="panel prose"><summary>来源质量与整理边界</summary><ul><li>年份、场次与题号按发布方页面标注，无法独立认证真实考场题序。</li><li>有歧义、条件不足的来源题会说明修订之处；未核实内容不补猜，不以原创题充作真题。</li><li>历史数字和合同假设只用于该题；规则更新需回到有效公告与法规核对。</li>${subject.isFund?RECALL_AUDIT_NOTES.map(note=>`<li>${esc(note)}</li>`).join(''):''}</ul></details>
 <section class="panel prose"><h2>官方与知识参考资料</h2><div class="sources">${primary.map(([,s])=>`<article>${link(s)}<p>${esc(s.note)}</p></article>`).join('')}</div></section>`;
}

export function academyGuide(subject) {
 const p=subject.PROFILES.standard,future=subject.id.startsWith('futures');
 return `${heading('EXAM RULES & STUDY SCOPE',`${subject.family} · 考试说明`,'考试形式、教学配比与资料依据，明确展示。')}<section class="panel prose"><h2>本科模拟规格</h2><div class="table-scroll"><table><thead><tr><th>题型</th><th>题量</th><th>本站每题计分</th><th>作答方式</th></tr></thead><tbody>${Object.entries(p.typeQuotas).map(([type,n])=>`<tr><td>${TYPE_NAMES[type]}</td><td>${n}</td><td>${future?p.typePoints[type]:'100 / 120 分'}</td><td>${type==='multiple'?'选全正确项，多选／少选／错选均不得分':'选择一个答案'}</td></tr>`).join('')}</tbody></table></div><p>${paperSize(p)} 题，${p.minutes} 分钟。${future?'100分制，总分60分达标；四种题型的题量与分值按协会公开考试介绍配置。':'正确率达到60%为本站达标线，成绩换算为100分显示。120题、120分钟与四种题型来自协会公告；60／30／20／10的题型数量是本站教学设置，并非官方公布命题权重。'}</p><p>依据：${link(subject.SOURCES[future?'futuresExam':'securitiesExam'])}。正式报考条件与当次考务要求以协会有效公告为准。</p></section><section class="panel prose"><h2>系统学习范围</h2><p>${subject.LESSONS.length} 章课程，从原理、概念辨析走到工作场景和计算案例，章末自测可接同章练习。这是主题式学习框架，不宣称已逐项展开指定教材与大纲的全部细则。</p><p>本科题库 ${subject.QUESTIONS.length} 道，其中 ${countHistorical(subject)} 道回忆真题重述。四种题型反复训练共同考点，参数变式独立标注，题量不等于独立知识点数量。</p><ul><li>单选、判断和综合题选择一个选项；多选题必须选全正确项。综合题为本站独立情景题，不模拟依赖前题答案的题组。</li><li>限时模拟离开页面仍继续计时，刷新可恢复；过期答卷会自动提交。交卷前不显示解析。</li><li>练习确认后计入掌握记录；结束练习只统计已确认题目。多选选择可以再次点击取消。</li><li>答案、错题、最近50次记录与阅读进度只保存在当前浏览器，各科独立。可在学习记录中导出备份。</li></ul></section><section class="panel prose"><h2>本科参考资料</h2><div class="sources">${Object.values(subject.SOURCES).filter(s=>s.kind==='official').map(s=>`<article>${link(s)}<p>${esc(s.note)}</p></article>`).join('')}</div><p>内容核对日期 ${CONTENT_DATE} · 版本 ${subject.BANK_VERSION}</p></section>`;
}

const plain = html => html.replace(/<[^>]+>/g,' ').replace(/&[a-z]+;/g,' ');
export function searchView(query,scope='current',subject,type='all',limit=20) {
 const tokens=query.trim().toLowerCase().split(/\s+/).filter(Boolean),subjects=scope==='all'?Object.values(SUBJECTS):[subject];
 const match=text=>tokens.every(token=>text.toLowerCase().includes(token));
 const lessons=tokens.length?subjects.flatMap(s=>s.LESSONS.filter(l=>match(`${l.title} ${l.intro} ${l.sections.map(section=>plain(section.html)).join(' ')}`)).map(l=>({s,l}))):[];
 const questions=tokens.length?subjects.flatMap(s=>s.QUESTIONS.filter(q=>match(`${q.stem} ${q.topic} ${q.options.join(' ')}`)).map(q=>({s,q}))):[];
 return `${heading('SEARCH THE KNOWLEDGE SYSTEM','找到考点，也找到它的原理。','搜索当前科目或全部八科的课程与题目。题目搜索不提前展示答案。')}<form id="knowledge-search" class="search-page-form"><label class="sr-only" for="search-query">搜索关键词</label><input id="search-query" name="query" value="${esc(query)}" placeholder="例如：久期、适当性、基金净值" maxlength="100" type="search"><button class="primary" type="submit">搜索</button></form><div class="search-controls"><label for="search-scope">搜索范围<select id="search-scope"><option value="current" ${scope==='current'?'selected':''}>当前科目</option><option value="all" ${scope==='all'?'selected':''}>全部八科</option></select></label><label for="search-type">内容类型<select id="search-type"><option value="all" ${type==='all'?'selected':''}>全部内容</option><option value="theory" ${type==='theory'?'selected':''}>理论课程</option><option value="question" ${type==='question'?'selected':''}>练习题目</option></select></label><p role="status">${tokens.length?`找到 ${lessons.length} 章课程、${questions.length} 道题`:'输入关键词开始搜索'}</p></div>
 ${type!=='question'&&lessons.length?`<div class="section-title"><h2>理论课程</h2><span>${lessons.length} 章</span></div><div class="search-results">${lessons.slice(0,limit).map(({s,l})=>`<a class="panel search-result" href="?subject=${s.id}#course/${l.id}"><span class="tiny-label">${s.short} · ${l.minutes} 分钟</span><h3>${esc(l.title)}</h3><p>${esc(l.intro)}</p><span>阅读原理与案例 →</span></a>`).join('')}</div>`:''}
 ${type!=='theory'&&questions.length?`<div class="section-title"><h2>练习题目</h2><span>${questions.length} 道</span></div><div class="search-results">${questions.slice(0,limit).map(({s,q})=>`<a class="panel search-result search-question" href="?subject=${s.id}#practice?question=${encodeURIComponent(q.id)}"><div class="question-badges"><span>${s.short}</span><span>${TYPE_NAMES[questionType(q)]}</span><span>${sourceLabel(q)}</span></div><h3>${esc(q.stem)}</h3><span>定位这道练习 →</span></a>`).join('')}</div>`:''}
 ${tokens.length&&!lessons.length&&!questions.length?'<section class="empty-state"><h2>暂时没有匹配内容</h2><p>试试更短的考点名称，或把搜索范围切换到全部八科。</p></section>':''}
 ${(type!=='question'&&lessons.length>limit)||(type!=='theory'&&questions.length>limit)?button('显示更多结果','search-more','','secondary full'):''}
 ${!tokens.length?'<div class="search-suggestions"><span>试着搜索</span>'+['基金净值','风险','适当性','期权','久期'].map(term=>button(term,'search-term',`data-term="${term}"`,'secondary')).join('')+'</div>':''}`;
}
