import { FUND_CONFIGS, FUND_SOURCES } from './fund-config.js';
const link = s => `<a href="${s.url}" target="_blank" rel="noopener noreferrer">${s.title}</a>`;
const heading = (title,desc) => `<div class="page-heading"><div><span class="eyebrow">CHINA · FUND QUALIFICATION</span><h1>${title}</h1><p>${desc}</p></div></div>`;
export function fundHome(subject,attempted,resume) {
 return `${heading('中国大陆基金从业资格',`当前：${subject.short}《${subject.name}》`)}
 <div class="fund-subject-tabs" aria-label="基金考试科目">${Object.values(FUND_CONFIGS).map(c=>`<a class="${c.id===subject.id?'selected':''}" ${c.id===subject.id?'aria-current="page"':''} href="?subject=${c.id}"><span>科目${['','一','二','三'][c.number]}</span><strong>${c.name}</strong></a>`).join('')}</div>${resume}
 <div class="home-grid"><section><div class="featured fund-featured"><div class="featured-copy"><span class="featured-label">${subject.short} · 原创题库，按正式规格计时计分</span><h2>从理解开始，把基础学扎实。</h2><p>5 章核心教程，100 道原创单选题。<br>交卷后看解析，按薄弱章节继续练习。</p><div class="exam-metrics"><div><strong>100<span> 题</span></strong><small>每题 1 分</small></div><div><strong>120<span> 分钟</span></strong><small>到时自动交卷</small></div><div><strong>60<span> 分</span></strong><small>模拟合格线</small></div></div><button class="light-primary" data-action="start-exam" data-profile="standard">开始本科模拟</button></div></div>
 <div class="section-title"><h2>按章节学习</h2><span>阅读 → 练习 → 复盘</span></div><div class="fund-lesson-cards">${subject.LESSONS.map((l,i)=>`<a class="panel" href="?subject=${subject.id}#course/${l.id}" data-action="course-open" data-lesson="${l.id}"><span class="eyebrow">CHAPTER 0${i+1}</span><h3>${l.title}</h3><p>${l.intro}</p><span>阅读 ${l.minutes} 分钟 · 对应 20 道练习</span></a>`).join('')}</div></section>
 <aside class="right-column fund-right"><section class="panel progress-panel"><h2>本科练习进度</h2><div class="progress-overview"><div class="progress-ring" style="--progress:${attempted}%"><div><strong>${attempted}</strong><span>/ 100 题</span></div></div><p>作答、错题和阅读进度<br>按科目分别保存</p></div><button class="secondary full" data-action="nav" data-view="practice">开始专项练习</button></section><section class="panel prose"><h2>先选清科目</h2><p>科目一为基础与法规；科目二侧重证券投资；科目三侧重私募股权的募投管退。具体应试组合与注册路径，按岗位和协会现行规定确认。</p><button class="text-button" data-action="nav" data-view="guide">查看考试说明</button></section><section class="panel prose"><h2>真题与资料</h2><p>官方大纲、考试公告和第三方历年回忆题入口分开标注。站内300题均为原创模拟。</p><button class="secondary full" data-action="nav" data-view="resources">打开真题资料</button></section></aside></div>
 <div class="rule-note"><p>核对日期：2026-09-29。题型与计分参照协会考试公告；本站每模块20题为教学安排，不是官方命题权重。当前每科题库100题，模拟会使用全库并随机排列，重复组卷会遇到相同题目。</p></div>`;
}
export function fundGuide(subject) {
 return `${heading('基金从业考试说明','考试合格、科目组合与资格注册是不同问题。')}<section class="panel prose"><h2>考试规格</h2><div class="table-scroll"><table><thead><tr><th>科目</th><th>名称</th><th>题量 / 时间</th><th>合格线</th></tr></thead><tbody>${Object.values(FUND_CONFIGS).map(c=>`<tr><td>${c.short}</td><td>${c.name}</td><td>100道单选 / 120分钟</td><td>60分，每题1分</td></tr>`).join('')}</tbody></table></div><p>闭卷计算机考试。组合型题目同样以单选方式作答，本站不添加多选或判断题计分。依据：${link(FUND_SOURCES.exam)}。不将期权开户考试的70分线或分项门槛套入基金从业考试。</p></section>
 <section class="panel prose"><h2>使用哪个版本？</h2><p>科目一现名《基金基础知识与法律法规》，旧称《基金法律法规、职业道德与业务规范》。协会2026-06-30发布新版大纲，自2026年9月行业专场考试起启用。当前教程按2026大纲梳理核心知识，考试场次、教材与适用规则仍应查看当次通知。</p><p>科目一的绩效考核、廉洁与纪法等新增参考规范，以及科目三私募监管、信息披露等更新，需结合官方原文学习。本站15章是核心导学，未声称覆盖大纲全部条目。</p><p>${link(FUND_SOURCES.update)} · ${link(FUND_SOURCES.notices)}</p></section>
 <section class="panel prose"><h2>通过后是否自动拿证？</h2><p>考试成绩合格不等于自动完成从业资格注册。科目组合、岗位范围及其他认定路径需查协会现行服务指南，并结合所在机构办理。不要把“一＋二”和“一＋三”理解为对所有岗位都可任意互换。</p><p>${link(FUND_SOURCES.registration)}</p></section>
 <section class="panel prose"><h2>本站怎样练习？</h2><ul><li>当前科目100题，五个教学模块各20题。三个科目共300题，其中180道概念与情景题、120道计算案例；计算案例含同类公式的不同参数训练。所有题目均为原创模拟，不是真题。</li><li>每科单独组卷、计分、保存答卷、错题与最近50次学习记录。模拟交卷前不显示答案，未作答计零分，按绝对截止时间计时；切换科目或离开页面不会暂停。</li><li>题库每科恰好100题，因此整卷覆盖本科全部题目，按教学模块随机排列；没有宣称每次生成全新试题。</li><li>练习确认后可查看解析，答错进入错题本，重练答对移出。提前结束练习只统计已确认题目。</li><li>各题链接用于定位官方大纲考点范围，不表示题目来自协会，也不表示大纲逐条提供本站解析。</li><li>费用、估值与分配计算以题设假设为准。涉及新规具体比例、期限、人员资格等，应回到有效规则原文核对。</li></ul><p>题库版本：${subject.BANK_VERSION}。科目切换不会清除期权学习记录；数据仅保存在当前浏览器。</p></section>`;
}
const recall = [
 {title:'科目一 · 历年回忆题目录',url:'https://ks.233.com/1188/2',note:'检索可见2026年5月不完整版（考生回忆版，82题）及历年目录。以来源页面实际开放内容为准。'},
 {title:'科目二 · 历年题目整理目录',url:'https://ks.233.com/1189/2',note:'目录含2026年5月及历史整理题。第三方对“真题/完整版”的标注未经本站逐题核验，不作为官方原卷。'},
 {title:'三个科目 · 历年回忆资料索引',url:'https://www.233.com/jjcy/zhenti/',note:'含法规、证券投资与私募股权分类入口。发布方说明相关题目来自考生回忆或网络汇总。'},
];
export function fundResources() {
 return `${heading('真题资料与官方大纲','先辨来源，再看年份和适用大纲。')}<section class="panel prose"><span class="soft-badge">来源核对 2026-09-29</span><h2>怎样理解这里的“真题”？</h2><p>本次未核实到协会公开发布的历年完整官方原卷。协会考试公告提示警惕以提供真题为名的诈骗。下方提供第三方历年整理与考生回忆资料入口，不能视作官方认证，本站也未复制这些试卷或用原创题冒充真题。</p><div class="table-scroll"><table><thead><tr><th>类别</th><th>本站提供</th><th>使用方法</th></tr></thead><tbody><tr><td>官方资料</td><td>公告、大纲原文链接</td><td>核对范围、规则和变化</td></tr><tr><td>历年回忆</td><td>第三方目录外链</td><td>核对年份、答案与现行规则</td></tr><tr><td>原创模拟</td><td>300道站内练习＋逐题解析</td><td>按章训练、计时自测、错题复习</td></tr></tbody></table></div><p>旧题尤其注意科目一改名与2026大纲更新；外部站点可能要求登录、使用App或付费，本站不保证免费开放或持续可用。</p></section>
 <section class="panel prose"><h2>历年回忆题入口</h2><div class="sources">${recall.map(s=>`<article><span class="soft-badge">第三方 · 非官方原卷</span><h3>${link(s)}</h3><p>${s.note}</p></article>`).join('')}</div><p>来源性质说明：<a href="https://www.233.com/jjcy/jichu/zhenti/202505/23160155798191.html" target="_blank" rel="noopener noreferrer">233网校关于考生回忆 / 网络汇总的说明</a>。仅核对页面和目录标注，没有核验全部试题及答案。</p><button class="primary" data-action="nav" data-view="practice">练习当前科目原创题</button></section>
 <section class="panel prose"><h2>官方资料</h2><div class="sources">${Object.values(FUND_SOURCES).map(s=>`<article>${link(s)}<p>${s.note}</p></article>`).join('')}</div><p>考试报名请从协会官网确认官方入口，避免通过来源不明的代报名渠道提交个人资料。</p></section>`;
}
