import { FUND_CONFIGS, FUND_SOURCES } from './fund-config.js';
import { FUND_UNITS, outlineCoverage } from './fund-curriculum.js';
import { RECALL_SOURCES, RECALL_AUDIT_NOTES } from './fund-recall-data.js';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link = s => `<a href="${s.url}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a>`;
const heading = (title,desc) => `<div class="page-heading"><div><span class="eyebrow">CHINA · FUND QUALIFICATION</span><h1>${title}</h1><p>${desc}</p></div></div>`;
const recalls=subject=>subject.QUESTIONS.filter(q=>q.sourceKind==='recall');
export function fundYearOptions(subject,selected=0) {
 return `<option value="0">全部年份</option>${[...new Set(recalls(subject).map(q=>q.year))].sort((a,b)=>b-a).map(y=>`<option value="${y}" ${Number(selected)===y?'selected':''}>${y}年</option>`).join('')}`;
}
export function fundHome(subject,attempted,resume) {
 const count=subject.QUESTIONS.length,recallCount=recalls(subject).length,objectives=outlineCoverage(subject.id).length;
 return `${heading('中国大陆基金从业资格',`当前：${subject.short}《${subject.name}》`)}
 <div class="fund-subject-tabs" aria-label="基金考试科目">${Object.values(FUND_CONFIGS).map(c=>`<a class="${c.id===subject.id?'selected':''}" ${c.id===subject.id?'aria-current="page"':''} href="?subject=${c.id}"><span>科目${['','一','二','三'][c.number]}</span><strong>${c.name}</strong></a>`).join('')}</div>${resume}
 <div class="home-grid"><section><div class="featured fund-featured"><div class="featured-copy"><span class="featured-label">2026 大纲逐章学习 · 历年回忆题独立标注</span><h2>把知识学全，再把薄弱处练透。</h2><p>${subject.LESSONS.length} 章教程 · ${count} 道题<br>${count-recallCount} 道原创模拟＋${recallCount} 道历年回忆题重述</p><div class="exam-metrics"><div><strong>100<span> 题</span></strong><small>从扩充题库抽取</small></div><div><strong>120<span> 分钟</span></strong><small>到时自动交卷</small></div><div><strong>60<span> 分</span></strong><small>模拟合格线</small></div></div><button class="light-primary" data-action="start-exam" data-profile="standard">开始本科模拟</button></div></div>
 <div class="fund-coverage-banner"><div><span class="eyebrow">按官方范围查漏</span><h2>${FUND_UNITS[subject.id].length} 个官方章节 · ${objectives} 条考试要求</h2><p>逐条列出原文、对应讲解与同节练习，细目可回到大纲核对。</p></div><button class="secondary" data-action="nav" data-view="coverage">查看大纲清单 →</button></div>
 <div class="section-title"><h2>2026 大纲逐章教程</h2><span>讲解 → 自测 → 同节练习</span></div><div class="fund-lesson-cards">${subject.LESSONS.slice(5).map(l=>`<a class="panel" href="?subject=${subject.id}#course/${l.id}" data-action="course-open" data-lesson="${l.id}"><span class="eyebrow">大纲第 ${l.officialChapter} 章</span><h3>${l.title}</h3><p>${l.intro}</p><span>${l.objectives.length} 条要求 · ${subject.QUESTIONS.filter(q=>q.chapter===l.practice).length} 道练习</span></a>`).join('')}</div>
 <details class="fund-intro panel"><summary>零基础先读：5 章入门与计算</summary><div class="fund-lesson-cards">${subject.LESSONS.slice(0,5).map(l=>`<a href="?subject=${subject.id}#course/${l.id}" data-action="course-open" data-lesson="${l.id}"><h3>${l.title}</h3><p>${l.intro}</p><span>阅读 ${l.minutes} 分钟 · 20 道练习</span></a>`).join('')}</div></details></section>
 <aside class="right-column fund-right"><section class="panel progress-panel"><h2>本科练习进度</h2><div class="progress-overview"><div class="progress-ring" style="--progress:${attempted/count*100}%"><div><strong>${attempted}</strong><span>/ ${count} 题</span></div></div><p>作答、错题和阅读进度<br>按科目分别保存</p></div><button class="secondary full" data-action="nav" data-view="practice">开始专项练习</button></section><section class="panel prose"><h2>历年题，能追溯</h2><p>站内可练 ${recallCount} 道历年回忆题，逐题标注场次、发布方、原文题号和整理说明。可以按来源、年份筛选。</p><button class="secondary full" data-action="nav" data-view="resources">打开真题资料</button></section><section class="panel prose"><h2>先选清科目</h2><p>一：基础与法规；二：证券投资；三：私募股权。科目组合和资格注册按岗位及协会规定确认。</p><button class="text-button" data-action="nav" data-view="guide">查看考试说明</button></section></aside></div>
 <div class="rule-note"><p>核对日期：2026-09-29。模拟每卷100题：入门模块20题，官方章节对应模块80题；配比为教学安排，不是官方命题权重。回忆题非官方原卷；大纲清单表示范围对应，不等于教材所有细则均已展开。</p></div>`;
}
export function fundGuide(subject) {
 return `${heading('基金从业考试说明','考试合格、科目组合与资格注册是不同问题。')}<section class="panel prose"><h2>考试规格</h2><div class="table-scroll"><table><thead><tr><th>科目</th><th>名称</th><th>题量 / 时间</th><th>合格线</th></tr></thead><tbody>${Object.values(FUND_CONFIGS).map(c=>`<tr><td>${c.short}</td><td>${c.name}</td><td>100道单选 / 120分钟</td><td>60分，每题1分</td></tr>`).join('')}</tbody></table></div><p>闭卷计算机考试，含普通及组合型单选。依据：${link(FUND_SOURCES.exam)}。报名与考试规则以当次公告为准。</p></section>
 <section class="panel prose"><h2>大纲与课程范围</h2><p>科目一现名《基金基础知识与法律法规》，旧称《基金法律法规、职业道德与业务规范》。2026大纲于6月30日发布，自2026年9月行业专场考试起启用。</p><p>三科共50章教程：15章入门＋35章官方章节对应讲解。大纲清单收录413条要求（科一108、科二153、科三152），逐项连接对应章节，并展示同节练习数量。这是查漏索引，不表示每条要求都有一题独占对应，也不表示教材和法规全部细目已展开。</p><p>涉及人员准入、薪酬绩效、纪法责任、税种税率、上市条件、披露期限及例外的细表，以及教材的历史阶段划分，需结合指定教材与有效规则逐项学习；读完导学不能代替这些内容。</p><p>${link(FUND_SOURCES.update)} · ${link(FUND_SOURCES.notices)}</p><button class="secondary" data-action="nav" data-view="coverage">核对本科全部大纲要求</button></section>
 <section class="panel prose"><h2>本站怎样练习？</h2><ul><li>当前科目 ${subject.QUESTIONS.length} 题，其中 ${recalls(subject).length} 道有来源的历年回忆题重述。三科共670题：652道原创模拟和18道回忆题整理；历史题的费率、条件不代表现行通用规则。</li><li>按章节、原创／回忆来源及年份筛选；回忆题详情可查看原始页面与整理说明。未找到可核实的协会公开完整原卷，不将回忆题称为官方原题。</li><li>每套模拟从本科题库按教学章节抽100题，卷内不重复；重复考试仍可能碰到相同题。章节配比并非官方权重。</li><li>模拟交卷前不显示答案。离开页面、切换科目或刷新不暂停计时，到期自动交卷；每科独立保存答卷、错题和最近50次记录。</li><li>练习确认后显示解析，答错入错题本，重练答对移出；提前结束仅统计已确认题。原有题号、阅读进度和旧版答卷继续兼容。</li><li>官方大纲用于定位范围，不代表协会认可本站自编讲解或解析。</li></ul><p>题库版本：${subject.BANK_VERSION}。记录仅保存在当前浏览器。</p></section>
 <section class="panel prose"><h2>通过后是否自动拿证？</h2><p>考试合格不等于自动完成从业资格注册。科目组合、岗位范围及其他认定路径需查协会现行指南，并结合所在机构办理。</p><p>${link(FUND_SOURCES.registration)}</p></section>`;
}
export function fundResources(subject,year=0) {
 const qs=recalls(subject).filter(q=>!year||q.year===year);
 return `${heading('真题资料与官方大纲',`${subject.short} · 站内回忆题、原始出处与官方范围`)}<section class="panel prose"><span class="soft-badge">来源核对 2026-09-29</span><h2>历年回忆题，可直接练</h2><p>本次未核实到协会公开发布的完整历年原卷。下列精选题来自第三方公开考后整理，保留来源题的考查关系、主要数值，以本站文字重述并独立复核解析；不是逐字原题，也不是官方认证试卷。点击逐题出处可以对照发布方原文。</p><p>站内三科共18道精选回忆题（2023—2026年，不同科目年份不同），与652道原创模拟分别标注。未批量转载第三方题库；缺题、付费内容及答案存疑的题目不补猜。</p><div class="fund-filter-row"><label for="recall-year">回忆题年份<select id="recall-year">${fundYearOptions(subject,year)}</select></label><button class="primary" data-action="recall-practice" data-year="${year}">练习这 ${qs.length} 道回忆题</button></div></section>
 <section class="recall-list" aria-label="历年回忆题">${qs.map(q=>`<article class="panel recall-question"><div class="question-badges"><span>${q.examSession}</span><span>${RECALL_SOURCES[q.source].publisher}</span><span>回忆题 · 重述</span></div><h2>${esc(q.stem)}</h2><ol type="A">${q.options.map(o=>`<li>${esc(o)}</li>`).join('')}</ol><details><summary>查看答案、解析与整理说明</summary><p><strong>正确答案：${'ABCD'[q.answer]}</strong></p><p>${esc(q.explanation)}</p><p class="muted">${esc(q.reviewNote)}</p></details><p class="source">出处：${link(RECALL_SOURCES[q.source])} · 来源页面第 ${q.sourceQuestion} 题 · 非官方原卷</p><a href="?subject=${subject.id}#course/${q.lessonId}" data-action="course-open" data-lesson="${q.lessonId}">回到对应章节 →</a></article>`).join('')}</section>
 <details class="panel prose"><summary>来源质量与未收录说明</summary><ul>${RECALL_AUDIT_NOTES.map(t=>`<li>${t}</li>`).join('')}</ul><p>来源页面的年度、题号为发布方标注；本站无法独立认证真实考场题序。过时规则、舍入口径和合同假设均需复核。</p></details>
 <section class="panel prose"><h2>更多历年回忆资料</h2><p><a href="https://www.233.com/jjcy/zhenti/" target="_blank" rel="noopener noreferrer">233网校 · 三科历年资料目录</a>。外部页面可能需要登录、App或付费，其“完整版”标注不代表本站核验或官方认证。</p><div class="sources">${Object.values(RECALL_SOURCES).filter(s=>s.subject===subject.id).map(s=>`<article>${link(s)}<p>${s.publisher} · ${s.session} · 本站仅整理所列精选题</p></article>`).join('')}</div></section>
 <section class="panel prose"><h2>官方资料</h2><div class="sources">${Object.entries(FUND_SOURCES).filter(([id])=>!RECALL_SOURCES[id]).map(([,s])=>`<article>${link(s)}<p>${s.note}</p></article>`).join('')}</div></section>`;
}
export function fundCoverage(subject,chapter=0) {
 const all=outlineCoverage(subject.id),units=FUND_UNITS[subject.id];
 return `${heading('2026 大纲查漏清单',`${subject.short} · ${units.length} 章、${all.length} 条官方考试要求`)}<section class="panel prose"><h2>每条要求，都有位置</h2><p>逐条保留官方大纲的编号和能力要求。点击“读本节”跳到章节，点击“原文”打开对应PDF页。“同节练习”是该节共用题量，不是每条要求的独立题量或掌握率。</p><p><strong>覆盖边界：</strong>清单覆盖大纲全部条目；本站讲解提供概念、公式、案例和辨析。教材细表、法规数字／期限／例外及新增规范全文需结合原文继续学习，不能据此推断已具备全部考试细节。</p><label for="coverage-chapter">筛选官方章节</label><select id="coverage-chapter"><option value="0">全部 ${units.length} 章</option>${units.map((u,i)=>`<option value="${i+1}" ${chapter===i+1?'selected':''}>${i+1}. ${u.title}</option>`).join('')}</select></section>
 <p class="muted">手机可横向滑动表格，查看对应讲解和原文链接。</p><div class="coverage-list">${units.map((u,i)=>({u,n:i+1})).filter(({n})=>!chapter||n===chapter).map(({u,n})=>{const rows=all.filter(o=>Number(o.code.split('.')[0])===n);return `<details class="panel coverage-chapter" ${chapter?'open':''}><summary>第 ${n} 章 · ${u.title}<span>${rows.length} 条要求</span></summary><div class="table-scroll"><table><thead><tr><th>编号</th><th>官方能力要求</th><th>章节对应</th><th>查阅</th></tr></thead><tbody>${rows.map(o=>`<tr class="coverage-objective"><td>${o.code}</td><td>${esc(o.text)}</td><td>${esc(o.section)}<small>同节练习 ${o.questionCount} 题</small></td><td><a href="?subject=${subject.id}#course/${o.lessonId}" data-action="course-open" data-lesson="${o.lessonId}" data-scope="${o.code.substring(0,o.code.lastIndexOf('.'))}">读本节</a> · <a href="${FUND_SOURCES[`outline${subject.number}`].url}#page=${o.page}" target="_blank" rel="noopener noreferrer">原文 p.${o.page}</a></td></tr>`).join('')}</tbody></table></div></details>`;}).join('')}</div>`;
}
