import { FUND_CONFIGS, FUND_SOURCES } from './fund-config.js';
import { FUND_UNITS, outlineCoverage } from './fund-curriculum.js';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link = s => `<a href="${s.url}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a>`;
const heading = (title,desc) => `<div class="page-heading"><div><span class="eyebrow">CHINA · FUND QUALIFICATION</span><h1>${title}</h1><p>${desc}</p></div></div>`;
const recalls=subject=>subject.QUESTIONS.filter(q=>q.sourceKind==='recall');
export function fundGuide(subject) {
 return `${heading('基金从业考试说明','考试合格、科目组合与资格注册是不同问题。')}<section class="panel prose"><h2>考试规格</h2><div class="table-scroll"><table><thead><tr><th>科目</th><th>名称</th><th>题量 / 时间</th><th>合格线</th></tr></thead><tbody>${Object.values(FUND_CONFIGS).map(c=>`<tr><td>${c.short}</td><td>${c.name}</td><td>100道单选 / 120分钟</td><td>60分，每题1分</td></tr>`).join('')}</tbody></table></div><p>闭卷计算机考试，含普通及组合型单选。依据：${link(FUND_SOURCES.exam)}。报名与考试规则以当次公告为准。</p></section>
 <section class="panel prose"><h2>大纲与课程范围</h2><p>科目一现名《基金基础知识与法律法规》，旧称《基金法律法规、职业道德与业务规范》。2026大纲于6月30日发布，自2026年9月行业专场考试起启用。</p><p>三科共50章教程：15章入门＋35章官方章节对应讲解。大纲清单收录413条要求（科一108、科二153、科三152），逐项连接对应章节，并展示同节练习数量。这是查漏索引，不表示每条要求都有一题独占对应，也不表示教材和法规全部细目已展开。</p><p>涉及人员准入、薪酬绩效、纪法责任、税种税率、上市条件、披露期限及例外的细表，以及教材的历史阶段划分，需结合指定教材与有效规则逐项学习；读完导学不能代替这些内容。</p><p>${link(FUND_SOURCES.update)} · ${link(FUND_SOURCES.notices)}</p><button class="secondary" data-action="nav" data-view="coverage">核对本科全部大纲要求</button></section>
 <section class="panel prose"><h2>本站怎样练习？</h2><ul><li>当前科目 ${subject.QUESTIONS.length} 题，其中 ${recalls(subject).length} 道有来源的历年回忆题重述，原创计算参数变式分别标注；历史题的费率、条件不代表现行通用规则。</li><li>按章节、原创／回忆来源及年份筛选；回忆题详情可查看原始页面与整理说明。未找到可核实的协会公开完整原卷，不将回忆题称为官方原题。</li><li>每套模拟从本科题库按教学章节抽100题，卷内不重复；重复考试仍可能碰到相同题。章节配比并非官方权重。</li><li>模拟交卷前不显示答案。离开页面、切换科目或刷新不暂停计时，到期自动交卷；每科独立保存答卷、错题和最近50次记录。</li><li>练习确认后显示解析，答错入错题本，重练答对移出；提前结束仅统计已确认题。原有题号、阅读进度和旧版答卷继续兼容。</li><li>官方大纲用于定位范围，不代表协会认可本站自编讲解或解析。</li></ul><p>题库版本：${subject.BANK_VERSION}。记录仅保存在当前浏览器，可以导出备份。</p></section>
 <section class="panel prose"><h2>通过后是否自动拿证？</h2><p>考试合格不等于自动完成从业资格注册。科目组合、岗位范围及其他认定路径需查协会现行指南，并结合所在机构办理。</p><p>${link(FUND_SOURCES.registration)}</p></section>`;
}
export function fundCoverage(subject,chapter=0) {
 const all=outlineCoverage(subject.id),units=FUND_UNITS[subject.id];
 return `${heading('2026 大纲查漏清单',`${subject.short} · ${units.length} 章、${all.length} 条官方考试要求`)}<section class="panel prose"><h2>每条要求，都有位置</h2><p>逐条保留官方大纲的编号和能力要求。点击“读本节”跳到章节，点击“原文”打开对应PDF页。“同节练习”是该节共用题量，不是每条要求的独立题量或掌握率。</p><p><strong>覆盖边界：</strong>清单覆盖大纲全部条目；本站讲解提供概念、公式、案例和辨析。教材细表、法规数字／期限／例外及新增规范全文需结合原文继续学习，不能据此推断已具备全部考试细节。</p><label for="coverage-chapter">筛选官方章节</label><select id="coverage-chapter"><option value="0">全部 ${units.length} 章</option>${units.map((u,i)=>`<option value="${i+1}" ${chapter===i+1?'selected':''}>${i+1}. ${u.title}</option>`).join('')}</select></section>
 <p class="muted">手机可横向滑动表格，查看对应讲解和原文链接。</p><div class="coverage-list">${units.map((u,i)=>({u,n:i+1})).filter(({n})=>!chapter||n===chapter).map(({u,n})=>{const rows=all.filter(o=>Number(o.code.split('.')[0])===n);return `<details class="panel coverage-chapter" ${chapter?'open':''}><summary>第 ${n} 章 · ${u.title}<span>${rows.length} 条要求</span></summary><div class="table-scroll"><table><thead><tr><th>编号</th><th>官方能力要求</th><th>章节对应</th><th>查阅</th></tr></thead><tbody>${rows.map(o=>`<tr class="coverage-objective"><td>${o.code}</td><td>${esc(o.text)}</td><td>${esc(o.section)}<small>同节练习 ${o.questionCount} 题</small></td><td><a href="?subject=${subject.id}#course/${o.lessonId}" data-action="course-open" data-lesson="${o.lessonId}" data-scope="${o.code.substring(0,o.code.lastIndexOf('.'))}">读本节</a> · <a href="${FUND_SOURCES[`outline${subject.number}`].url}#page=${o.page}" target="_blank" rel="noopener noreferrer">原文 p.${o.page}</a></td></tr>`).join('')}</tbody></table></div></details>`;}).join('')}</div>`;
}
